### ISSUE TITLE
more typos

### ISSUE THREAD

**Issue by vsug606** [Knutas/HelloHeroes#3]
support -> healer? (but support makes more sense.. lol)
mixed berry macarron -> mint macaroon?
also a few "att" that should be "atk"?

**Comment by Knutas** [comment]
I use support since I find it more accurate (a minority of the "healers" can actually heal).
I'm not sure if I prefer atk over att, but here I have chosen to use the same as in-game.

The macaroon name will be updated. Thanks!

**Comment by vsug606** [comment]
also.. succubus gianna not ginna  =P

**Comment by Knutas** [comment]
Thanks again!
