### ISSUE TITLE
Please Update

### ISSUE THREAD

**Issue by EJGS** [Knutas/HelloHeroes#7]
Please update with the latest stats and heroes from Season 4 (the cold betrayal)

**Comment by Knutas** [comment]
I stop playing HH at the beginning of this year and Gatekeeper has taken over the tedious task of updating the table. From what I heard from him there was a lot of changes in the recent update so it is taking some time to complete, but he is working on it and is hoping to finish before the end of this week.

If you'd like you can fork this project, make some additions and create a pull request, that would speed up the process.

**Comment by GatekeeperPH** [comment]
Hi,

Season 04 updates are now in place. Please let us know should you find errors in the database.
